import Vue from 'vue'
import { Button, Form, FormItem, Input, Checkbox, Row, Col, Icon, Link, Avatar, Dialog, Upload, Image, Dropdown, DropdownMenu, DropdownItem, Tabs, TabPane } from 'element-ui'

Vue.use(Button)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Input)
Vue.use(Checkbox)
Vue.use(Row)
Vue.use(Col)
Vue.use(Icon)
Vue.use(Link)
Vue.use(Avatar)
Vue.use(Dialog)
Vue.use(Upload)
Vue.use(Image)
Vue.use(Dropdown)
Vue.use(DropdownMenu)
Vue.use(DropdownItem)
Vue.use(Tabs)
Vue.use(TabPane)
